using System.Collections.Generic;
using System.Globalization;
using System.Threading;

namespace Recap
{
    public static class Localization
    {
        private static Dictionary<string, string> _dict;
        private static readonly Dictionary<string, Dictionary<string, string>> _languages = new Dictionary<string, Dictionary<string, string>>
        {
            {
                "en", new Dictionary<string, string>
                {
                    { "windowTitle", "Recap" },
                    { "statusWorking", "Status: Working" },
                    { "statusStopped", "Status: Stopped" },
                    { "liveFeed", "Autoscroll" },
                    { "quality", "Quality:" },
                    { "startWithWindows", "Start with Windows" },
                    { "folder", "Folder:" },
                    { "browse", "Browse..." },
                    { "fullscreen", "❐ Fullscreen" },
                    { "noRecordsFor", "No records for {0}." },
                    { "frame", "Frame {0} of {1}. File size: {2:F2} MB" },
                    { "errorReadingFile", "Error reading file: {0}" },
                    { "selectFolder", "Select a folder to store files." },
                    { "startBtn", "Start" },
                    { "stopBtn", "Stop" },
                    { "qualityLow", "Low (25)" },
                    { "qualityMedium", "Medium (45)" },
                    { "qualityHigh", "High (75)" },
                    { "qualityMax", "Maximum (95)" },
                    { "trayShow", "Show" },
                    { "trayExit", "Exit" },
                    { "settingsBtn", "Settings" },
                    { "settingsTitle", "Settings" },
                    { "lang", "Language:" },
                    { "monitor", "Monitor:" },
                    { "monitorAll", "All Monitors (Panorama)" },
                    { "freq", "Frequency:" },
                    { "blindZone", "Blind Zone:" },
                    { "motionThreshold", "Motion Threshold:" },
                    { "ok", "OK" },
                    { "cancel", "Cancel" },
                    { "standard", "(Standard)" },
                    { "tiny", "(Tiny)" },
                    { "extreme", "(Extreme)" },
                    { "allApps", "All Applications" },
                    { "filterApps", "Filter by app:" },
                    { "searchApps", "Search..." },
                    { "legacyApp", "📁 Legacy (old format)" },
                    { "dayViewTab", "Day View" },
                    { "statsTab", "Statistics" },
                    { "advancedSettings", "Advanced Settings" },
                    { "disableVideoPreviews", "Disable Video Previews" },
                    { "rangeMode", "Range Mode" },
                    { "tooltip_Language", "Select the application interface language." },
                    { "tooltip_Monitor", "Select the monitor to capture.\n'All Monitors' creates a large panorama but increases file size and CPU usage." },
                    { "tooltip_Quality", "Set the JPEG quality for screenshots. Higher quality means larger file size." },
                    { "tooltip_Frequency", "Set how often screenshots are taken." },
                    { "tooltip_BlindZone", "Used to ignore stopwatch changes on the clock." },
                    { "tooltip_MotionThreshold", "Sets the screen change sensitivity threshold.\nIf fewer pixels change than specified (e.g., 5%),\nthe screenshot will not be saved.\nSignificantly saves disk space." },
                    { "tooltip_GlobalSearch", "Enable experimental global search feature." },
                    { "tooltip_ShowFrameCount", "Frame count will be displayed instead of activity time." },
                    { "tooltip_EnableOCR", "Enable Optical Character Recognition to search text within images." },
                    { "tooltip_EnableHighlighting", "Highlight found text in the image viewer." },
                    { "tooltip_DisableVideoPreviews", "Disables loading of video covers. Previously loaded previews are saved in: {0}" },
                    { "refreshBtn", "Refresh" },
                    { "periodLabel", "Period:" },
                    { "globalSearch", "Global Search" },
                    { "ocrSearch", "OCR Search" },
                    { "selectRange", "Select Range..." },
                    { "globalSearchExp", "Global Search" },
                    { "showFrameCount", "Show Frame Count" },
                    { "enableOCR", "Enable OCR (Text Recognition)" },
                    { "enableHighlighting", "Enable Text Highlighting" },
                    { "hourlyActivity", "Hourly Activity" },
                    { "charts", "Charts" },
                    { "heatmap", "Heatmap" },
                    { "chartDay", "Day" },
                    { "chartWeek", "Week (7 days)" },
                    { "chartMonth", "Month" },
                    { "chartAll", "All Time" },
                    { "chartReset", "Reset Filter" },
                    { "loadingData", "Loading data..." },
                    { "activityTooltip", "{0}:00 - {1}:00\nActivity: {2}h {3}m" },
                    { "interval_5fps", "5 FPS" },
                    { "interval_2fps", "2 FPS" },
                    { "interval_1fps", "1 FPS" },
                    { "interval_0_5fps", "0.5 FPS (2s)" },
                    { "interval_3s", "1 per 3s" },
                    { "interval_5s", "1 per 5s" },
                    { "interval_10s", "1 per 10s" },
                    { "interval_30s", "1 per 30s" },
                    { "periodWeek", "Last Week" },
                    { "periodMonth", "Last Month" },
                    { "periodAll", "All Time" },
                    { "periodCustom", "Custom Range" }
                }
            },
            {
                "ru", new Dictionary<string, string>
                {
                    { "windowTitle", "Recap" },
                    { "statusWorking", "Статус: Работает" },
                    { "statusStopped", "Статус: Остановлено" },
                    { "liveFeed", "Автоперемотка" },
                    { "quality", "Качество:" },
                    { "startWithWindows", "Запускать с Windows" },
                    { "folder", "Папка:" },
                    { "browse", "Обзор..." },
                    { "fullscreen", "❐ На весь экран" },
                    { "noRecordsFor", "Нет записей за {0}." },
                    { "frame", "Кадр {0} из {1}. Размер файла: {2:F2} МБ" },
                    { "errorReadingFile", "Ошибка чтения файла: {0}" },
                    { "selectFolder", "Выберите папку для хранения файлов." },
                    { "startBtn", "Старт" },
                    { "stopBtn", "Стоп" },
                    { "qualityLow", "Низкое (25)" },
                    { "qualityMedium", "Среднее (45)" },
                    { "qualityHigh", "Высокое (75)" },
                    { "qualityMax", "Максимальное (95)" },
                    { "trayShow", "Показать" },
                    { "trayExit", "Выход" },
                    { "settingsBtn", "Настройки" },
                    { "settingsTitle", "Настройки" },
                    { "lang", "Язык:" },
                    { "monitor", "Монитор:" },
                    { "monitorAll", "Все мониторы (Панорама)" },
                    { "freq", "Частота:" },
                    { "blindZone", "Слепая зона:" },
                    { "motionThreshold", "Порог движения:" },
                    { "ok", "ОК" },
                    { "cancel", "Отмена" },
                    { "standard", "(Стандарт)" },
                    { "tiny", "(Маленькая)" },
                    { "extreme", "(Экстрим)" },
                    { "allApps", "Все приложения" },
                    { "filterApps", "Фильтр по приложению:" },
                    { "searchApps", "Поиск..." },
                    { "legacyApp", "📁 Старый формат" },
                    { "dayViewTab", "Просмотр дня" },
                    { "statsTab", "Статистика" },
                    { "advancedSettings", "Расширенные настройки" },
                    { "disableVideoPreviews", "Отключить превью видео" },
                    { "rangeMode", "Период" },
                    { "tooltip_Language", "Выберите язык интерфейса приложения." },
                    { "tooltip_Monitor", "Выберите монитор для захвата.\n'Все мониторы' создает большую панораму, но увеличивает размер файлов и нагрузку." },
                    { "tooltip_Quality", "Установите качество JPEG для скриншотов. Более высокое качество означает больший размер файла." },
                    { "tooltip_Frequency", "Установите частоту создания скриншотов." },
                    { "tooltip_BlindZone", "Используется для того, чтобы игнорировать изменения секундомера на часах." },
                    { "tooltip_MotionThreshold", "Устанавливает порог чувствительности\nизменений на экране. Если изменилось\nменьше пикселей, чем указано (например, 5%),\nскриншот не будет сохранен.\nСущественно экономит место на диске." },
                    { "tooltip_GlobalSearch", "Включить экспериментальную функцию глобального поиска." },
                    { "tooltip_ShowFrameCount", "Количество кадров будет отображаться вместо времени активности." },
                    { "tooltip_EnableOCR", "Включить оптическое распознавание символов для поиска текста на изображениях." },
                    { "tooltip_EnableHighlighting", "Подсвечивать найденный текст в просмотрщике изображений." },
                    { "tooltip_DisableVideoPreviews", "Отключает загрузку обложек видео. Ранее загруженные превью сохраняются в папке: {0}" },
                    { "refreshBtn", "Обновить" },
                    { "periodLabel", "Период:" },
                    { "globalSearch", "Глобальный поиск" },
                    { "ocrSearch", "OCR Поиск" },
                    { "selectRange", "Выбрать диапазон..." },
                    { "globalSearchExp", "Глобальный поиск" },
                    { "showFrameCount", "Показывать количество кадров" },
                    { "enableOCR", "Включить OCR (Распознавание текста)" },
                    { "enableHighlighting", "Включить подсветку текста" },
                    { "hourlyActivity", "Активность по часам" },
                    { "charts", "Диаграммы" },
                    { "heatmap", "Тепловая карта" },
                    { "chartDay", "День" },
                    { "chartWeek", "Неделя (7 дней)" },
                    { "chartMonth", "Месяц" },
                    { "chartAll", "Все время" },
                    { "chartReset", "Сброс фильтра" },
                    { "loadingData", "Загрузка данных..." },
                    { "activityTooltip", "{0}:00 - {1}:00\nАктивность: {2}ч {3}м" },
                    { "interval_5fps", "5 FPS" },
                    { "interval_2fps", "2 FPS" },
                    { "interval_1fps", "1 FPS" },
                    { "interval_0_5fps", "0.5 FPS (2с)" },
                    { "interval_3s", "1 раз в 3с" },
                    { "interval_5s", "1 раз в 5с" },
                    { "interval_10s", "1 раз в 10с" },
                    { "interval_30s", "1 раз в 30с" },
                    { "periodWeek", "За неделю" },
                    { "periodMonth", "За месяц" },
                    { "periodAll", "За всё время" },
                    { "periodCustom", "Пользовательский" }
                }
            },
            {
                "uk", new Dictionary<string, string>
                {
                    { "windowTitle", "Recap" },
                    { "statusWorking", "Статус: Працює" },
                    { "statusStopped", "Статус: Зупинено" },
                    { "liveFeed", "Автоперемотка" },
                    { "quality", "Якість:" },
                    { "startWithWindows", "Запускати з Windows" },
                    { "folder", "Тека:" },
                    { "browse", "Огляд..." },
                    { "fullscreen", "❐ На весь екран" },
                    { "noRecordsFor", "Немає записів за {0}." },
                    { "frame", "Кадр {0} з {1}. Розмір файлу: {2:F2} МБ" },
                    { "errorReadingFile", "Помилка читання файлу: {0}" },
                    { "selectFolder", "Виберіть теку для зберігання файлів." },
                    { "startBtn", "Старт" },
                    { "stopBtn", "Стоп" },
                    { "qualityLow", "Низька (25)" },
                    { "qualityMedium", "Середня (45)" },
                    { "qualityHigh", "Висока (75)" },
                    { "qualityMax", "Максимальна (95)" },
                    { "trayShow", "Показати" },
                    { "trayExit", "Вихід" },
                    { "settingsBtn", "Налаштування" },
                    { "settingsTitle", "Налаштування" },
                    { "lang", "Мова:" },
                    { "monitor", "Монітор:" },
                    { "monitorAll", "Всі монітори (Панорама)" },
                    { "freq", "Частота:" },
                    { "blindZone", "Сліпа зона:" },
                    { "motionThreshold", "Поріг руху:" },
                    { "ok", "ОК" },
                    { "cancel", "Скасувати" },
                    { "standard", "(Стандарт)" },
                    { "tiny", "(Крихітна)" },
                    { "extreme", "(Екстрим)" },
                    { "allApps", "Всі програми" },
                    { "filterApps", "Фільтр за програмою:" },
                    { "searchApps", "Пошук..." },
                    { "legacyApp", "📁 Старий формат" },
                    { "dayViewTab", "Перегляд дня" },
                    { "statsTab", "Статистика" },
                    { "advancedSettings", "Розширені налаштування" },
                    { "disableVideoPreviews", "Вимкнути прев'ю відео" },
                    { "rangeMode", "Період" },
                    { "tooltip_Language", "Виберіть мову інтерфейсу програми." },
                    { "tooltip_Monitor", "Виберіть монітор для захоплення.\n'Всі монітори' створює велику панораму, але збільшує розмір файлів і навантаження." },
                    { "tooltip_Quality", "Встановіть якість JPEG для скріншотів. Вища якість означає більший розмір файлу." },
                    { "tooltip_Frequency", "Встановіть частоту створення скріншотів." },
                    { "tooltip_BlindZone", "Використовується для того, щоб ігнорувати зміни секундоміра на годиннику." },
                    { "tooltip_MotionThreshold", "Встановлює поріг чутливості\nзмін на екрані. Якщо змінилося\nменше пікселів, ніж вказано (наприклад, 5%),\nскріншот не буде збережено.\nСуттєво економить місце на диску." },
                    { "tooltip_GlobalSearch", "Увімкнути експериментальну функцію глобального пошуку." },
                    { "tooltip_ShowFrameCount", "Кількість кадрів буде відображатися замість часу активності." },
                    { "tooltip_EnableOCR", "Увімкнути оптичне розпізнавання символів для пошуку тексту на зображеннях." },
                    { "tooltip_EnableHighlighting", "Підсвічувати знайдений текст у переглядачі зображень." },
                    { "tooltip_DisableVideoPreviews", "Вимкнути завантаження обкладинок відео. Раніше завантажені прев'ю зберігаються в папці: {0}" },
                    { "refreshBtn", "Оновити" },
                    { "periodLabel", "Період:" },
                    { "globalSearch", "Глобальний пошук" },
                    { "ocrSearch", "OCR Пошук" },
                    { "selectRange", "Вибрати діапазон..." },
                    { "globalSearchExp", "Глобальний пошук" },
                    { "showFrameCount", "Показувати кількість кадрів" },
                    { "enableOCR", "Увімкнути OCR (Розпізнавання тексту)" },
                    { "enableHighlighting", "Увімкнути підсвічування тексту" },
                    { "hourlyActivity", "Активність по годинах" },
                    { "charts", "Діаграми" },
                    { "heatmap", "Теплова карта" },
                    { "chartDay", "День" },
                    { "chartWeek", "Тиждень (7 днів)" },
                    { "chartMonth", "Місяць" },
                    { "chartAll", "Весь час" },
                    { "chartReset", "Скинути фільтр" },
                    { "loadingData", "Завантаження даних..." },
                    { "activityTooltip", "{0}:00 - {1}:00\nАктивність: {2}год {3}хв" },
                    { "interval_5fps", "5 FPS" },
                    { "interval_2fps", "2 FPS" },
                    { "interval_1fps", "1 FPS" },
                    { "interval_0_5fps", "0.5 FPS (2с)" },
                    { "interval_3s", "1 раз на 3с" },
                    { "interval_5s", "1 раз на 5с" },
                    { "interval_10s", "1 раз на 10с" },
                    { "interval_30s", "1 раз на 30с" },
                    { "periodWeek", "За тиждень" },
                    { "periodMonth", "За місяць" },
                    { "periodAll", "За весь час" },
                    { "periodCustom", "Користувацький" }
                }
            }
        };

        public static void SetLanguage(string lang)
        {
            _dict = _languages.ContainsKey(lang) ? _languages[lang] : _languages["en"];
            
            try
            {
                var culture = new CultureInfo(lang);
                Thread.CurrentThread.CurrentCulture = culture;
                Thread.CurrentThread.CurrentUICulture = culture;
            }
            catch { }
        }

        public static string Get(string key)
        {
            if (_dict == null) SetLanguage("en");
            return _dict.ContainsKey(key) ? _dict[key] : $"<{key}>";
        }

        public static string Format(string key, params object[] args)
        {
            return string.Format(Get(key), args);
        }
    }
}