using System.Collections.Generic;
using System.Globalization;
using System.Threading;

namespace Recap
{
    public static class Localization
    {
        private static Dictionary<string, string> _dict;
        private static readonly Dictionary<string, Dictionary<string, string>> _languages = new Dictionary<string, Dictionary<string, string>>
        {
            {
                "en", new Dictionary<string, string>
                {
                    { "windowTitle", "Recap" },
                    { "statusWorking", "Status: Working" },
                    { "statusStopped", "Status: Stopped" },
                    { "liveFeed", "Autoscroll" },
                    { "quality", "Quality:" },
                    { "startWithWindows", "Start with Windows" },
                    { "folder", "Folder:" },
                    { "browse", "Browse..." },
                    { "fullscreen", "❐ Fullscreen" },
                    { "noRecordsFor", "No records for {0}." },
                    { "frame", "Frame {0} of {1}. File size: {2:F2} MB" },
                    { "errorReadingFile", "Error reading file: {0}" },
                    { "selectFolder", "Select a folder to store files." },
                    { "startBtn", "Start" },
                    { "stopBtn", "Stop" },
                    { "qualityLow", "Low (25)" },
                    { "qualityMedium", "Medium (45)" },
                    { "qualityHigh", "High (75)" },
                    { "qualityMax", "Maximum (95)" },
                    { "trayShow", "Show" },
                    { "trayExit", "Exit" },
                    { "settingsBtn", "Settings" },
                    { "settingsTitle", "Settings" },
                    { "lang", "Language:" },
                    { "monitor", "Monitor:" },
                    { "monitorAll", "All Monitors (Panorama)" },
                    { "freq", "Frequency:" },
                    { "blindZone", "Blind Zone:" },
                    { "motionThreshold", "Motion Threshold:" },
                    { "ok", "OK" },
                    { "cancel", "Cancel" },
                    { "standard", "(Standard)" },
                    { "tiny", "(Tiny)" },
                    { "extreme", "(Extreme)" },
                    { "allApps", "All Applications" },
                    { "filterApps", "Filter by app:" },
                    { "searchApps", "Search..." },
                    { "legacyApp", "📁 Legacy (old format)" },
                    { "dayViewTab", "Day View" },
                    { "statsTab", "Statistics" },
                    { "advancedSettings", "Advanced Settings" },
                    { "disableVideoPreviews", "Disable Video Previews" },
                    { "rangeMode", "Range Mode" },
                    { "tooltip_Language", "Select the application interface language." },
                    { "tooltip_Monitor", "Select the monitor to capture.\n'All Monitors' creates a large panorama but increases file size and CPU usage." },
                    { "tooltip_Quality", "Set the JPEG quality for screenshots. Higher quality means larger file size." },
                    { "tooltip_Frequency", "Set how often screenshots are taken." },
                    { "tooltip_BlindZone", "Used to ignore stopwatch changes on the clock." },
                    { "tooltip_MotionThreshold", "Sets the screen change sensitivity threshold.\nIf fewer pixels change than specified (e.g., 5%),\nthe screenshot will not be saved.\nSignificantly saves disk space." },
                    { "tooltip_GlobalSearch", "Enable experimental global search feature." },
                    { "tooltip_ShowFrameCount", "Frame count will be displayed instead of activity time." },
                    { "tooltip_EnableOCR", "Enable Optical Character Recognition to search text within images." },
                    { "tooltip_EnableHighlighting", "Highlight found text in the image viewer." },
                    { "tooltip_DisableVideoPreviews", "Disables loading of video covers. Previously loaded previews are saved in: {0}" },
                    { "refreshBtn", "Refresh" },
                    { "periodLabel", "Period:" },
                    { "globalSearch", "Global Search" },
                    { "ocrSearch", "OCR Search" },
                    { "selectRange", "Select Range..." },
                    { "globalSearchExp", "Global Search" },
                    { "showFrameCount", "Show Frame Count" },
                    { "enableOCR", "Enable OCR (Text Recognition)" },
                    { "enableHighlighting", "Enable Text Highlighting" },
                    { "hourlyActivity", "Hourly Activity" },
                    { "charts", "Charts" },
                    { "heatmap", "Heatmap" },
                    { "chartDay", "Day" },
                    { "chartWeek", "Week (7 days)" },
                    { "chartMonth", "Month" },
                    { "chartAll", "All Time" },
                    { "chartReset", "Reset Filter" },
                    { "loadingData", "Loading data..." },
                    { "totalMonthActivity", "Total activity for the month: {0} hours" },
                    { "totalTime", "Total time: {0}" },
                    { "rangePickerTitle", "Select Range" },
                    { "rangePickerStart", "Start Date:" },
                    { "rangePickerEnd", "End Date:" },
                    { "excludeApp", "Exclude application" },
                    { "activityTooltip", "{0}:00 - {1}:00\nActivity: {2}h {3}m" },
                    { "activity", "Activity" },
                    { "timeFormatFull", "{0}h {1}m {2}s" },
                    { "timeFormatShort", "{0}h {1}m" },
                    { "timeFormatMinSec", "{0}m {1}s" },
                    { "timeFormatSec", "{0}s" },
                    { "interval_5fps", "5 FPS" },
                    { "interval_2fps", "2 FPS" },
                    { "interval_1fps", "1 FPS" },
                    { "interval_0_5fps", "0.5 FPS (2s)" },
                    { "interval_3s", "1 per 3s" },
                    { "interval_5s", "1 per 5s" },
                    { "interval_10s", "1 per 10s" },
                    { "interval_30s", "1 per 30s" },
                    { "periodWeek", "Last Week" },
                    { "periodMonth", "Last Month" },
                    { "periodAll", "All Time" },
                    { "periodCustom", "Custom Range" },
                    { "extWarnTitle", "Browser Extension Required" },
                    { "extWarnText", "To ensure Recap works correctly (tracking URLs and YouTube video titles), you need to install the browser extension.\n\n1. Open your browser (Chrome/Edge/Brave).\n2. Go to chrome://extensions\n3. Enable 'Developer mode' (top right).\n4. Click 'Load unpacked'.\n5. Select the 'browser-extension' folder located in the application directory." },
                    { "extWarnDontShow", "Don't show this again" },
                    { "extWarnOpenFolder", "Open extension folder" },
                    { "copyImage", "Copy Image" },
                    { "viewText", "View Text on Image" },
                    { "ocrTextTitle", "Recognized Text" },
                    { "copyText", "Copy Text" },
                    { "notes", "Notes:" },
                    { "addNoteTitle", "Add Note" },
                    { "noteTitleLabel", "Title:" },
                    { "noteDescLabel", "Description:" },
                    { "noteExistsError", "A note with this title already exists. Please add a number, for example." },
                    { "error", "Error" },
                    { "deleteNote", "Delete Note" },
                    { "helpTitle", "Help & Controls" },
                    { "helpNavigation", "Navigation" },
                    { "helpNotes", "Notes" },
                    { "helpPrevNext", "Previous / Next Frame" },
                    { "helpWheel", "Seek 5 frames" },
                    { "helpCtrlWheel", "Seek 10 frames" },
                    { "helpShiftWheel", "Seek 100 frames" },
                    { "helpCreateNote", "Create new note at current frame" },
                    { "helpToggleNotes", "Show/Hide Notes Panel" },
                    { "helpDeleteNote", "Delete note (on note item)" },
                    { "or", "or" },
                    { "mouseWheel", "Mouse Wheel" },
                    { "rightClick", "Right Click" },
                    { "rename", "Rename" },
                    { "resetName", "Reset Name" },
                    { "enterNewName", "Enter new name:" },
                    { "aliasDuplicateWarning", "Name already exists. Suggested:" }
                }
            },
            {
                "ru", new Dictionary<string, string>
                {
                    { "windowTitle", "Recap" },
                    { "statusWorking", "Статус: Работает" },
                    { "statusStopped", "Статус: Остановлено" },
                    { "liveFeed", "Автоперемотка" },
                    { "quality", "Качество:" },
                    { "startWithWindows", "Запускать с Windows" },
                    { "folder", "Папка:" },
                    { "browse", "Обзор..." },
                    { "fullscreen", "❐ На весь экран" },
                    { "noRecordsFor", "Нет записей за {0}." },
                    { "frame", "Кадр {0} из {1}. Размер файла: {2:F2} МБ" },
                    { "errorReadingFile", "Ошибка чтения файла: {0}" },
                    { "selectFolder", "Выберите папку для хранения файлов." },
                    { "startBtn", "Старт" },
                    { "stopBtn", "Стоп" },
                    { "qualityLow", "Низкое (25)" },
                    { "qualityMedium", "Среднее (45)" },
                    { "qualityHigh", "Высокое (75)" },
                    { "qualityMax", "Максимальное (95)" },
                    { "trayShow", "Показать" },
                    { "trayExit", "Выход" },
                    { "settingsBtn", "Настройки" },
                    { "settingsTitle", "Настройки" },
                    { "lang", "Язык:" },
                    { "monitor", "Монитор:" },
                    { "monitorAll", "Все мониторы (Панорама)" },
                    { "freq", "Частота:" },
                    { "blindZone", "Слепая зона:" },
                    { "motionThreshold", "Порог движения:" },
                    { "ok", "ОК" },
                    { "cancel", "Отмена" },
                    { "standard", "(Стандарт)" },
                    { "tiny", "(Маленькая)" },
                    { "extreme", "(Экстрим)" },
                    { "allApps", "Все приложения" },
                    { "filterApps", "Фильтр по приложению:" },
                    { "searchApps", "Поиск..." },
                    { "legacyApp", "📁 Старый формат" },
                    { "dayViewTab", "Просмотр дня" },
                    { "statsTab", "Статистика" },
                    { "advancedSettings", "Расширенные настройки" },
                    { "disableVideoPreviews", "Отключить превью видео" },
                    { "rangeMode", "Период" },
                    { "tooltip_Language", "Выберите язык интерфейса приложения." },
                    { "tooltip_Monitor", "Выберите монитор для захвата.\n'Все мониторы' создает большую панораму, но увеличивает размер файлов и нагрузку." },
                    { "tooltip_Quality", "Установите качество JPEG для скриншотов. Более высокое качество означает больший размер файла." },
                    { "tooltip_Frequency", "Установите частоту создания скриншотов." },
                    { "tooltip_BlindZone", "Используется для того, чтобы игнорировать изменения секундомера на часах." },
                    { "tooltip_MotionThreshold", "Устанавливает порог чувствительности\nизменений на экране. Если изменилось\nменьше пикселей, чем указано (например, 5%),\nскриншот не будет сохранен.\nСущественно экономит место на диске." },
                    { "tooltip_GlobalSearch", "Включить экспериментальную функцию глобального поиска." },
                    { "tooltip_ShowFrameCount", "Количество кадров будет отображаться вместо времени активности." },
                    { "tooltip_EnableOCR", "Включить оптическое распознавание символов для поиска текста на изображениях." },
                    { "tooltip_EnableHighlighting", "Подсвечивать найденный текст в просмотрщике изображений." },
                    { "tooltip_DisableVideoPreviews", "Отключает загрузку обложек видео. Ранее загруженные превью сохраняются в папке: {0}" },
                    { "refreshBtn", "Обновить" },
                    { "periodLabel", "Период:" },
                    { "globalSearch", "Глобальный поиск" },
                    { "ocrSearch", "OCR Поиск" },
                    { "selectRange", "Выбрать диапазон..." },
                    { "globalSearchExp", "Глобальный поиск" },
                    { "showFrameCount", "Показывать количество кадров" },
                    { "enableOCR", "Включить OCR (Распознавание текста)" },
                    { "enableHighlighting", "Включить подсветку текста" },
                    { "hourlyActivity", "Активность по часам" },
                    { "charts", "Диаграммы" },
                    { "heatmap", "Тепловая карта" },
                    { "chartDay", "День" },
                    { "totalMonthActivity", "Общее время активности за месяц - {0} часов" },
                    { "totalTime", "Всего времени {0}" },
                    { "rangePickerTitle", "Выбрать период" },
                    { "rangePickerStart", "Начало:" },
                    { "rangePickerEnd", "Конец:" },
                    { "chartWeek", "Неделя (7 дней)" },
                    { "chartMonth", "Месяц" },
                    { "chartAll", "Все время" },
                    { "chartReset", "Сброс фильтра" },
                    { "loadingData", "Загрузка данных..." },
                    { "excludeApp", "Исключить приложение" },
                    { "activityTooltip", "{0}:00 - {1}:00\nАктивность: {2}ч {3}м" },
                    { "activity", "Активность" },
                    { "timeFormatFull", "{0}ч {1}м {2}с" },
                    { "timeFormatShort", "{0}ч {1}м" },
                    { "timeFormatMinSec", "{0}м {1}с" },
                    { "timeFormatSec", "{0}с" },
                    { "interval_5fps", "5 FPS" },
                    { "interval_2fps", "2 FPS" },
                    { "interval_1fps", "1 FPS" },
                    { "interval_0_5fps", "0.5 FPS (2с)" },
                    { "interval_3s", "1 раз в 3с" },
                    { "interval_5s", "1 раз в 5с" },
                    { "interval_10s", "1 раз в 10с" },
                    { "interval_30s", "1 раз в 30с" },
                    { "periodWeek", "За неделю" },
                    { "periodMonth", "За месяц" },
                    { "periodAll", "За всё время" },
                    { "periodCustom", "Пользовательский" },
                     { "extWarnTitle", "Требуется расширение браузера" },
                    { "extWarnText", "Для корректной работы (отслеживание URL и названий видео на YouTube) необходимо установить расширение браузера.\n\n1. Откройте браузер (Chrome/Edge).\n2. Перейдите по адресу chrome://extensions\n3. Включите 'Режим разработчика' (вверху справа).\n4. Нажмите 'Загрузить распакованное расширение'.\n5. Выберите папку 'browser-extension', которая находится в папке с программой." },
                    { "extWarnDontShow", "Больше не показывать это окно" },
                    { "extWarnOpenFolder", "Открыть папку расширения" },
                    { "copyImage", "Копировать изображение" },
                    { "viewText", "Просмотреть текст на изображении" },
                    { "ocrTextTitle", "Распознанный текст" },
                    { "copyText", "Копировать текст" },
                    { "notes", "Заметки:" },
                    { "addNoteTitle", "Добавить заметку" },
                    { "noteTitleLabel", "Название:" },
                    { "noteDescLabel", "Описание:" },
                    { "noteExistsError", "Заметка с таким названием уже существует. Добавьте цифру, например." },
                    { "error", "Ошибка" },
                    { "deleteNote", "Удалить заметку" },
                    { "helpTitle", "Справка и управление" },
                    { "helpNavigation", "Навигация" },
                    { "helpNotes", "Заметки" },
                    { "helpPrevNext", "Предыдущий / Следующий кадр" },
                    { "helpWheel", "Перемотка на 5 кадров" },
                    { "helpCtrlWheel", "Перемотка на 10 кадров" },
                    { "helpShiftWheel", "Перемотка на 100 кадров" },
                    { "helpCreateNote", "Создать заметку на текущем кадре" },
                    { "helpToggleNotes", "Показать/Скрыть панель заметок" },
                    { "helpDeleteNote", "Удалить заметку (на элементе)" },
                    { "or", "или" },
                    { "mouseWheel", "Колесико мыши" },
                    { "rightClick", "ПКМ" },
                    { "rename", "Переименовать" },
                    { "resetName", "Сбросить название" },
                    { "enterNewName", "Введите новое название:" },
                    { "aliasDuplicateWarning", "Имя уже существует. Предлагается:" }
                }
            },
            {
                "uk", new Dictionary<string, string>
                {
                    { "windowTitle", "Recap" },
                    { "statusWorking", "Статус: Працює" },
                    { "statusStopped", "Статус: Зупинено" },
                    { "liveFeed", "Автоперемотка" },
                    { "quality", "Якість:" },
                    { "startWithWindows", "Запускати з Windows" },
                    { "folder", "Тека:" },
                    { "browse", "Огляд..." },
                    { "fullscreen", "❐ На весь екран" },
                    { "noRecordsFor", "Немає записів за {0}." },
                    { "frame", "Кадр {0} з {1}. Розмір файлу: {2:F2} МБ" },
                    { "errorReadingFile", "Помилка читання файлу: {0}" },
                    { "selectFolder", "Виберіть теку для зберігання файлів." },
                    { "startBtn", "Старт" },
                    { "stopBtn", "Стоп" },
                    { "qualityLow", "Низька (25)" },
                    { "qualityMedium", "Середня (45)" },
                    { "qualityHigh", "Висока (75)" },
                    { "qualityMax", "Максимальна (95)" },
                    { "trayShow", "Показати" },
                    { "trayExit", "Вихід" },
                    { "settingsBtn", "Налаштування" },
                    { "settingsTitle", "Налаштування" },
                    { "lang", "Мова:" },
                    { "monitor", "Монітор:" },
                    { "monitorAll", "Всі монітори (Панорама)" },
                    { "freq", "Частота:" },
                    { "blindZone", "Сліпа зона:" },
                    { "motionThreshold", "Поріг руху:" },
                    { "ok", "ОК" },
                    { "cancel", "Скасувати" },
                    { "standard", "(Стандарт)" },
                    { "tiny", "(Крихітна)" },
                    { "extreme", "(Екстрим)" },
                    { "allApps", "Всі програми" },
                    { "filterApps", "Фільтр за програмою:" },
                    { "searchApps", "Пошук..." },
                    { "legacyApp", "📁 Старий формат" },
                    { "dayViewTab", "Перегляд дня" },
                    { "statsTab", "Статистика" },
                    { "advancedSettings", "Розширені налаштування" },
                    { "disableVideoPreviews", "Вимкнути прев'ю відео" },
                    { "rangeMode", "Період" },
                    { "tooltip_Language", "Виберіть мову інтерфейсу програми." },
                    { "tooltip_Monitor", "Виберіть монітор для захоплення.\n'Всі монітори' створює велику панораму, але збільшує розмір файлів і навантаження." },
                    { "tooltip_Quality", "Встановіть якість JPEG для скріншотів. Вища якість означає більший розмір файлу." },
                    { "tooltip_Frequency", "Встановіть частоту створення скріншотів." },
                    { "tooltip_BlindZone", "Використовується для того, щоб ігнорувати зміни секундоміра на годиннику." },
                    { "tooltip_MotionThreshold", "Встановлює поріг чутливості\nзмін на екрані. Якщо змінилося\nменше пікселів, ніж вказано (наприклад, 5%),\nскріншот не буде збережено.\nСуттєво економить місце на диску." },
                    { "tooltip_GlobalSearch", "Увімкнути експериментальну функцію глобального пошуку." },
                    { "tooltip_ShowFrameCount", "Кількість кадрів буде відображатися замість часу активності." },
                    { "tooltip_EnableOCR", "Увімкнути оптичне розпізнавання символів для пошуку тексту на зображеннях." },
                    { "tooltip_EnableHighlighting", "Підсвічувати знайдений текст у переглядачі зображень." },
                    { "tooltip_DisableVideoPreviews", "Вимкнути завантаження обкладинок відео. Раніше завантажені прев'ю зберігаються в папці: {0}" },
                    { "refreshBtn", "Оновити" },
                    { "periodLabel", "Період:" },
                    { "globalSearch", "Глобальний пошук" },
                    { "ocrSearch", "OCR Пошук" },
                    { "selectRange", "Вибрати діапазон..." },
                    { "globalSearchExp", "Глобальний пошук" },
                    { "showFrameCount", "Показувати кількість кадрів" },
                    { "enableOCR", "Увімкнути OCR (Розпізнавання тексту)" },
                    { "enableHighlighting", "Увімкнути підсвічування тексту" },
                    { "hourlyActivity", "Активність по годинах" },
                    { "charts", "Діаграми" },
                    { "heatmap", "Теплова карта" },
                    { "chartDay", "День" },
                    { "totalMonthActivity", "Загальний час активності за місяць - {0} годин" },
                    { "totalTime", "Всього часу {0}" },
                    { "rangePickerTitle", "Вибрати період" },
                    { "rangePickerStart", "Початок:" },
                    { "rangePickerEnd", "Кінець:" },
                    { "chartWeek", "Тиждень (7 днів)" },
                    { "chartMonth", "Місяць" },
                    { "chartAll", "Весь час" },
                    { "chartReset", "Скинути фільтр" },
                    { "loadingData", "Завантаження даних..." },
                    { "excludeApp", "Виключити застосунок" },
                    { "activityTooltip", "{0}:00 - {1}:00\nАктивність: {2}год {3}хв" },
                    { "activity", "Активність" },
                    { "timeFormatFull", "{0}г {1}х {2}с" },
                    { "timeFormatShort", "{0}г {1}х" },
                    { "timeFormatMinSec", "{0}х {1}с" },
                    { "timeFormatSec", "{0}с" },
                    { "interval_5fps", "5 FPS" },
                    { "interval_2fps", "2 FPS" },
                    { "interval_1fps", "1 FPS" },
                    { "interval_0_5fps", "0.5 FPS (2с)" },
                    { "interval_3s", "1 раз на 3с" },
                    { "interval_5s", "1 раз на 5с" },
                    { "interval_10s", "1 раз на 10с" },
                    { "interval_30s", "1 раз на 30с" },
                    { "periodWeek", "За тиждень" },
                    { "periodMonth", "За місяць" },
                    { "periodAll", "За весь час" },
                    { "periodCustom", "Користувацький" },
                    { "extWarnTitle", "Потрібне розширення браузера" },
                    { "extWarnText", "Для коректної роботи (відстеження URL та назв відео на YouTube ) необхідно встановити розширення браузера.\n\n1. Відкрийте браузер (Chrome/Edge).\n2. Перейдіть за адресою chrome://extensions\n3. Увімкніть 'Режим розробника' (згори праворуч).\n4. Натисніть 'Завантажити розпаковане розширення'.\n5. Виберіть теку 'browser-extension', яка знаходиться у теці з програмою." },
                    { "extWarnDontShow", "Більше не показувати це вікно" },
                    { "extWarnOpenFolder", "Відкрити теку розширення" },
                    { "copyImage", "Копіювати зображення" },
                    { "viewText", "Переглянути текст на зображенні" },
                    { "ocrTextTitle", "Розпізнаний текст" },
                    { "copyText", "Копіювати текст" },
                    { "notes", "Нотатки:" },
                    { "addNoteTitle", "Додати нотатку" },
                    { "noteTitleLabel", "Назва:" },
                    { "noteDescLabel", "Опис:" },
                    { "noteExistsError", "Нотатка з такою назвою вже існує. Додайте цифру, наприклад." },
                    { "error", "Помилка" },
                    { "deleteNote", "Видалити нотатку" },
                    { "helpTitle", "Довідка та керування" },
                    { "helpNavigation", "Навігація" },
                    { "helpNotes", "Нотатки" },
                    { "helpPrevNext", "Попередній / Наступний кадр" },
                    { "helpWheel", "Перемотка на 5 кадрів" },
                    { "helpCtrlWheel", "Перемотка на 10 кадрів" },
                    { "helpShiftWheel", "Перемотка на 100 кадрів" },
                    { "helpCreateNote", "Створити нотатку на поточному кадрі" },
                    { "helpToggleNotes", "Показати/Приховати панель нотаток" },
                    { "helpDeleteNote", "Видалити нотатку (на елементі)" },
                    { "or", "або" },
                    { "mouseWheel", "Коліщатко миші" },
                    { "rightClick", "ПКМ" },
                    { "rename", "Перейменувати" },
                    { "resetName", "Скинути назву" },
                    { "enterNewName", "Введіть нову назву:" },
                    { "aliasDuplicateWarning", "Назва вже існує. Пропонується:" }
                }
            }
        };

        public static void SetLanguage(string lang)
        {
            _dict = _languages.ContainsKey(lang) ? _languages[lang] : _languages["en"];
            
            try
            {
                var culture = new CultureInfo(lang);
                Thread.CurrentThread.CurrentCulture = culture;
                Thread.CurrentThread.CurrentUICulture = culture;
            }
            catch { }
        }

        public static string Get(string key)
        {
            if (_dict == null) SetLanguage("en");
            return _dict.ContainsKey(key) ? _dict[key] : $"<{key}>";
        }

        public static string Format(string key, params object[] args)
        {
            return string.Format(Get(key), args);
        }
    }
}